[project]
name = "llm-server"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "binghuis", email = "soongbinghui@gmail.com" }]
dependencies = ["fastapi>=0.110.2", "uvicorn[standard]>=0.29.0"]
requires-python = "==3.12.*"
readme = "README.md"
license = { text = "MIT" }

[tool.pdm]
distribution = false

[tool.pdm.scripts]
dev = "uvicorn src.llm_server.main:app --reload"
